---
# Requires:
#  $node_name
#  $friendly_name
#  $ap_ssid
#  $sensor_platform
#  $sensor_model
#  $t_offset

esphome:
  name: hvac-$node_name
  friendly_name: HVAC $friendly_name

esp8266:
  board: nodemcu

# Enable logging
logger:

<<: !include .inc_wifi-iot-ap.yaml

captive_portal:

i2c:
  sda: GPIO4 # D2 # GPIO4 for ESP8266 # GPIO21 for ESP32
  scl: GPIO5 # D1 # GPIO5 for ESP8266 # GPIO22 For ESP32
