sensor:
  - platform: htu21d
    model: HTU21D
    temperature:
      name: "Temperature"
      unit_of_measurement: °F
      filters: 
        - lambda: return (x * (9.0/5.0) + 32.0) + $t_offset;
    humidity:
      name: "Humidity"
    update_interval: 60s