esphome:
  name: hvac-garage
  friendly_name: HVAC Garage

esp8266:
  board: nodemcu

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "86ln5Gqy/s5rtL4ouzqcke96sHNojEDoEx7P9JzjF6g="

ota:
  - platform: esphome
    password: "92f263e922c89db839c492289a83b15f"

wifi:
  ssid: !secret iot_wifi_ssid
  password: !secret iot_wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Hvac-Garage Fallback Hotspot"
    password: "D9GT9F146uzU"

captive_portal:
    
i2c:
  sda: GPIO4 # D2 # GPIO4 for ESP8266 # GPIO21 for ESP32
  scl: GPIO5 # D1 # GPIO5 for ESP8266 # GPIO22 For ESP32

sensor:
  - platform: htu21d
    model: htu21d
    temperature:
      name: "Temperature"
      unit_of_measurement: °F
      filters: 
        - lambda: return x * (9.0/5.0) + 32.0;
    humidity:
      name: "Humidity"