---
substitutions:
  node_name: family-room-north
  friendly_name: Family Room North
  ap_ssid: HVAC_FM_North
  t_offset: "-3"

packages:
  - !include .pkg_hvac-base.yaml
  - !include .pkg_hvac-aht10.yaml

ota:
  - platform: esphome
    password: "28f4ee2fd15d2a531220e6fa7c371474"