---
substitutions:
  node_name: garage
  friendly_name: Garage
  ap_ssid: HVAC_Garage
  t_offset: "-6.6"

packages:
  - !include .pkg_hvac-base.yaml
  - !include .pkg_hvac-htu21d.yaml

ota:
  - platform: esphome
    password: "92f263e922c89db839c492289a83b15f"