# Can wake up for extented time by connecting CK pin to 3v3 (right side of C4)
# Press the boot btn during led flashing at start up to calibrate the battery. Battery must be fully charged!

esphome:
  name: hvac-remote-guest-room
  friendly_name: HVAC Remote Guest Room
  platformio_options:
    upload_speed: 921600
  includes:
    - <Arduino.h>
    - <OneWire.h>
    - <DallasTemperature.h>
  libraries:
    - milesburton/DallasTemperature@^3.9.1
  on_boot:
    priority: 750
    then:
      - output.turn_on: owpwr
      - output.turn_on: status_led1
  on_shutdown:
    - priority: 750
      then:
        - output.turn_off: owpwr
        - output.turn_off: status_led1

esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
  - source: github://evotodi/EspHomeComponents
  # - source: C:\Users\Justin\Documents\Projects\EspHomeComponents\components
    refresh: 0s
    components: [ batt18650stats, ds18powered, wake_reason ]

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "JIVZXsmkraPn7LB3dXQ968FgiTdCIZaElHNWnb+Gn+c="

ota:
  - platform: esphome
    password: "d84cceda222179d444adbbe480921aee"

wifi:
  ssid: !secret iot_wifi_ssid
  password: !secret iot_wifi_password

deep_sleep:
  id: deep_sleep1
  run_duration:
    default: 15s
    gpio_wakeup_reason: 5min
  sleep_duration: 10min
  wakeup_pin: GPIO13
  wakeup_pin_mode: KEEP_AWAKE

output:
  - platform: gpio
    pin: GPIO22
    id: owpwr
  - platform: gpio
    pin: GPIO2
    id: status_led1

batt18650stats:
  id: batt1
  adc_pin: GPIO36
  cal_pin: GPIO0
  led_output: status_led1
  reads: 10
  v_min: 2.8
  v_max: 4.15
  low_charge: 20

ds18powered:
  id: ds18p1
  ow_pin: GPIO21
  pwr_output: owpwr

sensor:
  - platform: ds18powered
    temp_sensor:
      name: temperature
      unit_of_measurement: °F
      accuracy_decimals: 2
      filters: 
        - lambda: return x * (9.0/5.0) + 32.0;

  - platform: batt18650stats
    voltage_sensor:
      name: voltage
    charge_sensor:
      name: charge

binary_sensor:
  - platform: batt18650stats      
    batt_low_sensor:
      name: battery    

text_sensor:
  - platform: wake_reason
    name: wake reason
    