---
substitutions:
  node_name: family-room-north
  friendly_name: Family Room North
  ap_ssid: HVAC_FM_North
  t_offset: "0"

packages:
  !include .pkg_hvac-aht10.yaml

<<: !include .inc_hvac-base.yaml