---
substitutions:
  node_name: laundry-room
  friendly_name: Laundry Room
  ap_ssid: HVAC_Laundry
  t_offset: "0"

packages:
  - !include .pkg_hvac-base.yaml
  - !include .pkg_hvac-aht10.yaml

ota:
  - platform: esphome
    password: "f67e139f6b4175900452fde95fb79f9f"