---
substitutions:
  node_name: living-room-ceiling
  friendly_name: Living Room Ceiling
  ap_ssid: HVAC_LR_Ceil
  t_offset: "0"

packages:
  !include .pkg_hvac-aht10.yaml

<<: !include .inc_hvac-base.yaml