---
substitutions:
  node_name: master-bath
  friendly_name: Master Bath
  ap_ssid: HVAC_MBath
  t_offset: "0"

packages:
  - !include .pkg_hvac-base.yaml
  - !include .pkg_hvac-htu21d.yaml

ota:
  - platform: esphome
    password: "909a3414afb4ca285a89ab69cdb52af0"