---
substitutions:
  node_name: living-room-ceiling
  friendly_name: Living Room Ceiling
  ap_ssid: HVAC_LR_Ceil
  t_offset: "-22.6"

packages:
  - !include .pkg_hvac-base.yaml
  - !include .pkg_hvac-aht10.yaml

ota:
  - platform: esphome
    password: "a40d03bfcd04b71d9022212bd704ef67"