---
substitutions:
  node_name: living-room-south
  friendly_name: Living Room South
  ap_ssid: HVAC_LR_South
  t_offset: "0"

packages:
  - !include .pkg_hvac-base.yaml
  - !include .pkg_hvac-aht10.yaml

ota:
  - platform: esphome
    password: "ec129d43bc32bb22a2c4eae2b5156582"