---
substitutions:
  node_name: family-room-north
  friendly_name: Family Room North
  ap_ssid: HVAC_FM_North
  sensor_platform: aht10
  sensor_model: AHT20
  t_offset: "0"

<<: !include .inc_hvac-base.yaml