---
substitutions:
  node_name: family-room-south
  friendly_name: Family Room South
  ap_ssid: HVAC_FM_South
  t_offset: "-3"

packages:
  - !include .pkg_hvac-base.yaml
  - !include .pkg_hvac-aht10.yaml

ota:
  - platform: esphome
    password: "2fa6f450def8ef33d9f9f7f40fbbc925"