---
substitutions:
  node_name: family-room-south
  friendly_name: Family Room South
  ap_ssid: HVAC_FM_South
  sensor_platform: aht10
  sensor_model: AHT20
  t_offset: "0"

<<: !include .inc_hvac-base.yaml