---
substitutions:
  node_name: living-room-south
  friendly_name: Living Room South
  ap_ssid: HVAC_LR_South
  sensor_platform: aht10
  sensor_model: AHT20
  t_offset: "0"

<<: !include .inc_hvac-base.yaml