---
substitutions:
  node_name: hall-bath
  friendly_name: Hall Bath
  ap_ssid: HVAC_HBath
  t_offset: "-2.2"

packages:
  - !include .pkg_hvac-base.yaml
  - !include .pkg_hvac-aht10.yaml

ota:
  - platform: esphome
    password: "e360492e6c7e920bffb35f954e056156"