---
substitutions:
  node_name: living-room-south
  friendly_name: Living Room South
  ap_ssid: HVAC_LR_South
  t_offset: "0"

packages:
  !include .pkg_hvac-aht10.yaml

<<: !include .inc_hvac-base.yaml